[package]
name = "groth16_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib","staticlib"]

[dependencies]
bellman = "0.14.0"
bls12_381 = "0.8.0"
ff = "0.13.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
getrandom = { version = "0.2", features = ["js"] }

[profile.release]
lto = true
opt-level = 'z'

[build-dependencies]
cbindgen = "0.27"