[package]
name = "zkp"
version = "0.1.0"
edition = "2021"

[lib]
name = "zkp"
crate-type = ["cdylib","staticlib","rlib"]

[dependencies]
bellman = "0.14"
byteorder = "1"
ff = "0.13"
group = "0.13"
pairing = "0.23"
rand_core = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bls12_381 = "0.8"

pairing_ce = { git = "https://github.com/matter-labs/pairing.git" }
ff_ce = "0.14.3"
bellman_ce = { git = "https://github.com/DoraFactory/bellman.git" }


[dev-dependencies]
rand = "0.8"
subtle = "2.2.1"

[profile.release]
debug = true
