[package]
name = "zkp"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib","staticlib"]

#[dependencies]
#lambdaworks-groth16 = { path = "../lambdaworks/provers/groth16" }
#lambdaworks-math = { path = "../lambdaworks/math" }
#serde_json = "1.0"
#mlua = {version = "*", features = ["luajit", "vendored", "module", "async", "send", "serialize", "macros"]}


[dependencies]
bls12_381 = "0.8"
ff = "0.13"
group = "0.13"
groth16 = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.13"

[dev-dependencies]
bls12_381 = "0.8"
rand = "0.8"
subtle = "2.2.1"

[profile.release]
debug = true
