[package]
name = "zkp"
version = "0.1.0"
edition = "2021"

[lib]
name = "zkp"
crate-type = ["cdylib","staticlib","rlib"]

[dependencies]
bellman = "0.14"
byteorder = "1"
ff = "0.13"
group = "0.13"
pairing = "0.23"
rand_core = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bls12_381 = "0.8"

pairing_ce = { version = "=0.30.6", git="https://github.com/matter-labs/zksync-crypto.git", package = "zksync_pairing" }
ff_ce = { version = "=0.30.6", git="https://github.com/matter-labs/zksync-crypto.git", package = "zksync_ff" }
bellman_ce = { version = "=0.30.6", git="https://github.com/matter-labs/zksync-crypto.git", package = "zksync_bellman" }


[dev-dependencies]
rand = "0.8"
subtle = "2.2.1"

[profile.release]
debug = true
