[package]
name = "zkp"
version = "0.1.0"
edition = "2021"

[lib]
name = "zkp"
crate-type = ["staticlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

pairing_ce = { version = "=0.30", git="https://github.com/matter-labs/zksync-crypto.git", package = "zksync_pairing" }

codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
	"derive",
] }

[features]
default = ["std"]
std = [
    "codec/std",
]

[profile.release]
debug = true
panic = "abort"
