[package]
name = "groth16_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
lto = true
opt-level = 'z'

[build-dependencies]
cbindgen = "0.27"
