[build]
target = ["wasm32-unknown-emscripten"]

[rust]
lld = true

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "panic=abort", "-Zpanic_abort_tests"]

[target.wasm32-wasip1]
rustflags = [
    "--cfg=web_sys_unstable_apis",
]

[target.wasm64-unknown-unknown]
rustflags = [
    "--cfg=web_sys_unstable_apis",
]

[target.wasm32-unknown-emscripten]
rustflags = [
    "--cfg=web_sys_unstable_apis",
]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[env]
RUSTFLAGS = "-Z wasm-c-abi=spec"

