[build]
target = ["wasm32-wasip1"]

[rust]
lld = true


[target.wasm32-wasip1]
rustflags = [
    "--cfg=web_sys_unstable_apis",
]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[env]
RUSTFLAGS = "-Z wasm-c-abi=spec"

