/* This file was automatically generated by cbindgen. DO NOT EDIT. */

#ifndef GROTH16_WASM_H
#define GROTH16_WASM_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

int32_t rust_test(void);

#endif  /* GROTH16_WASM_H */
