/* This file was automatically generated by cbindgen. DO NOT EDIT. */

#ifndef ZKP_H
#define ZKP_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

const char *keccak(const char *input_ptr);

const char *verify(const char *input_ptr);

#endif  /* ZKP_H */
