/* This file was automatically generated by cbindgen. DO NOT EDIT. */

#ifndef ZKP_H
#define ZKP_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define MIMC_ROUNDS 322

/**
 * C-compatible verify function that takes a JSON string input
 */
int32_t verify(const char *input_ptr);

#endif  /* ZKP_H */
