/* This file was automatically generated by cbindgen. DO NOT EDIT. */

#ifndef ZKP_H
#define ZKP_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#endif  /* ZKP_H */
